### ISSUE TITLE
recreation rise rate is wrong

### ISSUE THREAD

**Issue by alp7292** [KonradHeinser/EBSGFramework#2] opened 2024-09-10 22:47 UTC
when i set it %50 in scenario multiplier and ate ambrosia it rise recratinon by 33 instead of 25 (ambrosia by default raises recreation by 50) and when i set it to %200 it raised recreation by 84 instead of 100 so something is wrong with calculations. it might be worth checking mood/comfort/beuty/psyfocus rise/fall rates bloodloss recovery etc. to make sure they work as intended

so far i tested

comfort fall rate (didnt tested rise rate)
beuty fall rate (didnt tested rise rate)
and they seem correct 
while recreation rise rate is wrong ,
 setting mood rise rate at %50 doesnt let mood to raise at all instead of slowing it by %50

also can you add outdoor/indoor rise/fall rate if possible i am using your framework for my scenarios and traits.

**Comment by KonradHeinser** [comment] 2024-09-11 12:22
Recreation rise rate fix has been uploaded
Still working on figuring out why mood is acting funny
Other stats appear to be working correctly, so it may just be those two having weird interactions with other systems
Added indoor/outdoor rise/fall stats to my list of stuff to work on

**Comment by KonradHeinser** [comment] 2024-09-12 11:42
Mood issue was caused by the stat being used twice. Should be working without issue now.

**Closed by KonradHeinser** 2024-09-12 11:42 UTC
